// <auto-generated />
using System;
using MerkERP.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MerkERP.DAL.Migrations
{
    [DbContext(typeof(MerkDbContext))]
    [Migration("20260716152618_AddSupplierTableMetadata")]
    partial class AddSupplierTableMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MerkERP.Core.Models.BarcodeType_s", b =>
                {
                    b.Property<long>("BarcodeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BarcodeTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BarcodeTypeId");

                    b.ToTable("BarcodeType_s");

                    b.HasData(
                        new
                        {
                            BarcodeTypeId = 1L,
                            Name = "EAN-13"
                        },
                        new
                        {
                            BarcodeTypeId = 2L,
                            Name = "EAN-8"
                        },
                        new
                        {
                            BarcodeTypeId = 3L,
                            Name = "UPC-A"
                        },
                        new
                        {
                            BarcodeTypeId = 4L,
                            Name = "UPC-E"
                        },
                        new
                        {
                            BarcodeTypeId = 5L,
                            Name = "Code 39"
                        },
                        new
                        {
                            BarcodeTypeId = 6L,
                            Name = "Code 128"
                        },
                        new
                        {
                            BarcodeTypeId = 7L,
                            Name = "ITF-14"
                        },
                        new
                        {
                            BarcodeTypeId = 8L,
                            Name = "GS1-128"
                        },
                        new
                        {
                            BarcodeTypeId = 9L,
                            Name = "QR Code"
                        },
                        new
                        {
                            BarcodeTypeId = 10L,
                            Name = "Data Matrix"
                        },
                        new
                        {
                            BarcodeTypeId = 11L,
                            Name = "Custom"
                        });
                });

            modelBuilder.Entity("MerkERP.Core.Models.Branch_cs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name_AR")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("InsertedBy");

                    b.ToTable("Branch_cs");
                });

            modelBuilder.Entity("MerkERP.Core.Models.Company_cs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Abbr")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("DefaultCurrencyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InternalCode")
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<string>("Name_AR")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaxId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DefaultCurrencyId");

                    b.HasIndex("InsertedBy");

                    b.HasIndex("InternalCode")
                        .IsUnique()
                        .HasFilter("[InternalCode] IS NOT NULL");

                    b.HasIndex("Name_EN")
                        .IsUnique();

                    b.ToTable("Company_cs");
                });

            modelBuilder.Entity("MerkERP.Core.Models.CurrencyExchangeRate_cs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ForBuying")
                        .HasColumnType("bit");

                    b.Property<bool>("ForSelling")
                        .HasColumnType("bit");

                    b.Property<long>("FromCurrencyId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<long>("ToCurrencyId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InsertedBy");

                    b.HasIndex("ToCurrencyId");

                    b.HasIndex("FromCurrencyId", "ToCurrencyId", "EffectiveDate")
                        .IsUnique();

                    b.ToTable("CurrencyExchangeRate_cs");
                });

            modelBuilder.Entity("MerkERP.Core.Models.Currency_s", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name_AR")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Currency_s");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "EGP",
                            IsActive = true,
                            Name_AR = "جنيه مصري",
                            Name_EN = "Egyptian Pound",
                            Symbol = "ج.م"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "USD",
                            IsActive = true,
                            Name_AR = "دولار أمريكي",
                            Name_EN = "US Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "EUR",
                            IsActive = true,
                            Name_AR = "يورو",
                            Name_EN = "Euro",
                            Symbol = "€"
                        });
                });

            modelBuilder.Entity("MerkERP.Core.Models.InventoryValidationMethod_s", b =>
                {
                    b.Property<long>("InventoryValidationMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InventoryValidationMethodId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InventoryValidationMethodId");

                    b.ToTable("InventoryValidationMethod_s");

                    b.HasData(
                        new
                        {
                            InventoryValidationMethodId = 1L,
                            Name = "FIFO"
                        },
                        new
                        {
                            InventoryValidationMethodId = 2L,
                            Name = "LIFO"
                        },
                        new
                        {
                            InventoryValidationMethodId = 3L,
                            Name = "Moving Average"
                        });
                });

            modelBuilder.Entity("MerkERP.Core.Models.ItemGroup_cs", b =>
                {
                    b.Property<long>("ItemGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ItemGroupId"));

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InternalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<string>("Name_AR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ParentItemGroupId")
                        .HasColumnType("bigint");

                    b.HasKey("ItemGroupId");

                    b.HasIndex("InsertedBy");

                    b.HasIndex("ParentItemGroupId");

                    b.ToTable("ItemGroup_cs");
                });

            modelBuilder.Entity("MerkERP.Core.Models.ItemType_s", b =>
                {
                    b.Property<long>("ItemTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ItemTypeId"));

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemTypeId");

                    b.HasIndex("InsertedBy");

                    b.ToTable("ItemType_s");

                    b.HasData(
                        new
                        {
                            ItemTypeId = 1L,
                            IsActive = true,
                            IsFavorite = false,
                            Name = "Stock Item"
                        },
                        new
                        {
                            ItemTypeId = 2L,
                            IsActive = true,
                            IsFavorite = false,
                            Name = "Service"
                        },
                        new
                        {
                            ItemTypeId = 3L,
                            IsActive = true,
                            IsFavorite = false,
                            Name = "Non-Stock Item"
                        });
                });

            modelBuilder.Entity("MerkERP.Core.Models.ItemUOMConversion_cs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ConversionFactor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("UOMId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InsertedBy");

                    b.HasIndex("ItemId");

                    b.HasIndex("UOMId");

                    b.ToTable("ItemUOMConversion_cs");
                });

            modelBuilder.Entity("MerkERP.Core.Models.Item_UOM_Barcode_cs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("BarcodeTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("UOMId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BarcodeTypeId");

                    b.HasIndex("ItemId");

                    b.HasIndex("UOMId");

                    b.ToTable("Item_UOM_Barcode_cs");
                });

            modelBuilder.Entity("MerkERP.Core.Models.Item_cs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AcceptSelling")
                        .HasColumnType("bit");

                    b.Property<long?>("DefaultPurchaseUOMId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DefaultSellingUOMId")
                        .HasColumnType("bigint");

                    b.Property<long>("DefaultUOMId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DefaultWarehouseId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InternalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("InventoryValidationMethodId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<long>("ItemGroupId")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemTypeId")
                        .HasColumnType("bigint");

                    b.Property<int?>("MinOrderQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Name_AR")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("OpeningStock")
                        .HasColumnType("bigint");

                    b.Property<long?>("SafetyStock")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DefaultPurchaseUOMId");

                    b.HasIndex("DefaultSellingUOMId");

                    b.HasIndex("DefaultUOMId");

                    b.HasIndex("DefaultWarehouseId");

                    b.HasIndex("InsertedBy");

                    b.HasIndex("InternalCode")
                        .IsUnique();

                    b.HasIndex("InventoryValidationMethodId");

                    b.HasIndex("ItemGroupId");

                    b.HasIndex("ItemTypeId");

                    b.ToTable("Item_cs");
                });

            modelBuilder.Entity("MerkERP.Core.Models.StockLedgerTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ActualQuantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InternalCode")
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("QuantityAfterTransaction")
                        .HasColumnType("decimal(18,4)");

                    b.Property<long>("StockTransactionTypeId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ValuationRate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<long>("WareHouseId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InsertedBy");

                    b.HasIndex("ItemId");

                    b.HasIndex("StockTransactionTypeId");

                    b.HasIndex("WareHouseId");

                    b.ToTable("StockLedgerTransaction");
                });

            modelBuilder.Entity("MerkERP.Core.Models.StockReconciliationTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InternalCode")
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("PostingDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("PostingTime")
                        .HasColumnType("time");

                    b.Property<long?>("SetWarehouseId")
                        .HasColumnType("bigint");

                    b.Property<long>("StockTransactionStatusId")
                        .HasColumnType("bigint");

                    b.Property<long>("StockTransactionTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InsertedBy");

                    b.HasIndex("SetWarehouseId");

                    b.HasIndex("StockTransactionStatusId");

                    b.HasIndex("StockTransactionTypeId");

                    b.ToTable("StockReconciliationTransaction");
                });

            modelBuilder.Entity("MerkERP.Core.Models.StockReconciliationTransactionDate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ChangeDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("StockReconciliationTransactionId")
                        .HasColumnType("bigint");

                    b.Property<long>("StockTransactionStatusId")
                        .HasColumnType("bigint");

                    b.Property<long>("StockTransactionTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InsertedBy");

                    b.HasIndex("StockReconciliationTransactionId");

                    b.HasIndex("StockTransactionStatusId");

                    b.HasIndex("StockTransactionTypeId");

                    b.ToTable("StockReconciliationTransactionDate");
                });

            modelBuilder.Entity("MerkERP.Core.Models.StockReconciliationTransactionDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<long>("StockReconciliationTransactionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UOMId")
                        .HasColumnType("bigint");

                    b.Property<long>("WarehouseId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InsertedBy");

                    b.HasIndex("ItemId");

                    b.HasIndex("StockReconciliationTransactionId");

                    b.HasIndex("UOMId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("StockReconciliationTransactionDetail");
                });

            modelBuilder.Entity("MerkERP.Core.Models.StockTransactionStatus_s", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Name_AR")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("StockTransactionStatus_s");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name_AR = "مسودة",
                            Name_EN = "Draft"
                        },
                        new
                        {
                            Id = 2L,
                            Name_AR = "قيد الانتظار",
                            Name_EN = "Pending"
                        },
                        new
                        {
                            Id = 3L,
                            Name_AR = "مُقدَّم",
                            Name_EN = "Submitted"
                        },
                        new
                        {
                            Id = 4L,
                            Name_AR = "ملغى",
                            Name_EN = "Cancelled"
                        },
                        new
                        {
                            Id = 5L,
                            Name_AR = "معدَّل",
                            Name_EN = "Amended"
                        });
                });

            modelBuilder.Entity("MerkERP.Core.Models.StockTransactionType_s", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Name_AR")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("StockTransactionType_s");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name_AR = "رصيد افتتاحي",
                            Name_EN = "Opening Balance"
                        },
                        new
                        {
                            Id = 2L,
                            Name_AR = "جرد المخزون",
                            Name_EN = "Stock Reconciliation"
                        },
                        new
                        {
                            Id = 3L,
                            Name_AR = "استلام مخزون",
                            Name_EN = "Stock Receipt"
                        },
                        new
                        {
                            Id = 4L,
                            Name_AR = "صرف مخزون",
                            Name_EN = "Stock Issue"
                        },
                        new
                        {
                            Id = 5L,
                            Name_AR = "تحويل مخزون",
                            Name_EN = "Stock Transfer"
                        });
                });

            modelBuilder.Entity("MerkERP.Core.Models.SupplierType_s", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name_AR")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("SupplierType_s");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name_AR = "شركة",
                            Name_EN = "Company"
                        },
                        new
                        {
                            Id = 2L,
                            Name_AR = "فرد",
                            Name_EN = "Individual"
                        },
                        new
                        {
                            Id = 3L,
                            Name_AR = "شراكة",
                            Name_EN = "Partnership"
                        });
                });

            modelBuilder.Entity("MerkERP.Core.Models.Supplier_cs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactMobile")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactPersonName")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("DefaultCurrencyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InternalCode")
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnHold")
                        .HasColumnType("bit");

                    b.Property<string>("Name_AR")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("SupplierTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("TaxId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DefaultCurrencyId");

                    b.HasIndex("InsertedBy");

                    b.HasIndex("InternalCode")
                        .IsUnique()
                        .HasFilter("[InternalCode] IS NOT NULL");

                    b.HasIndex("SupplierTypeId");

                    b.ToTable("Supplier_cs");
                });

            modelBuilder.Entity("MerkERP.Core.Models.TableMetaData", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("ColumnOrder")
                        .HasColumnType("int");

                    b.Property<int>("DataTypeId")
                        .HasColumnType("int");

                    b.Property<string>("EntityProperty")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FilterTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ForeignKeyProperty")
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsFilterable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSortable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LabelAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LabelEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MinWidth")
                        .HasColumnType("int");

                    b.Property<int>("RenderAsId")
                        .HasColumnType("int");

                    b.Property<int>("TableNameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataTypeId");

                    b.HasIndex("FilterTypeId");

                    b.HasIndex("RenderAsId");

                    b.HasIndex("TableNameId", "Key")
                        .IsUnique();

                    b.ToTable("TableMetaData");
                });

            modelBuilder.Entity("MerkERP.Core.Models.TableMetaData_DataType_s", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TableMetaData_DataType_s");
                });

            modelBuilder.Entity("MerkERP.Core.Models.TableMetaData_FilterType_s", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TableMetaData_FilterType_s");
                });

            modelBuilder.Entity("MerkERP.Core.Models.TableMetaData_RenderAs_s", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TableMetaData_RenderAs_s");
                });

            modelBuilder.Entity("MerkERP.Core.Models.TableName_s", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("EntityKey")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TableName_s");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "BarcodeType_s"
                        },
                        new
                        {
                            Id = 2,
                            EntityKey = "branches",
                            Name = "Branch_cs"
                        },
                        new
                        {
                            Id = 3,
                            Name = "InventoryValidationMethod_s"
                        },
                        new
                        {
                            Id = 4,
                            EntityKey = "items",
                            Name = "Item_cs"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Item_UOM_Barcode_cs"
                        },
                        new
                        {
                            Id = 6,
                            EntityKey = "itemgroups",
                            Name = "ItemGroup_cs"
                        },
                        new
                        {
                            Id = 7,
                            Name = "ItemType_s"
                        },
                        new
                        {
                            Id = 8,
                            Name = "ItemUOMConversion_cs"
                        },
                        new
                        {
                            Id = 10,
                            Name = "TableName_s"
                        },
                        new
                        {
                            Id = 11,
                            EntityKey = "uoms",
                            Name = "UOM_cs"
                        },
                        new
                        {
                            Id = 12,
                            EntityKey = "uomconversionfactors",
                            Name = "UOMConversionFactor_cs"
                        },
                        new
                        {
                            Id = 13,
                            EntityKey = "uomconversiongroups",
                            Name = "UOMConversionGroup_cs"
                        },
                        new
                        {
                            Id = 14,
                            EntityKey = "warehouses",
                            Name = "WareHouse_cs"
                        },
                        new
                        {
                            Id = 15,
                            EntityKey = "warehousecategories",
                            Name = "WareHouseCategory_cs"
                        },
                        new
                        {
                            Id = 16,
                            Name = "WareHouseType_s"
                        },
                        new
                        {
                            Id = 18,
                            Name = "TableMetaData"
                        },
                        new
                        {
                            Id = 19,
                            Name = "UserType_s"
                        },
                        new
                        {
                            Id = 20,
                            Name = "User_cs"
                        },
                        new
                        {
                            Id = 21,
                            Name = "StockTransactionType_s"
                        },
                        new
                        {
                            Id = 22,
                            Name = "StockReconciliationTransaction"
                        },
                        new
                        {
                            Id = 23,
                            Name = "StockReconciliationTransactionDetail"
                        },
                        new
                        {
                            Id = 24,
                            Name = "StockLedgerTransaction"
                        },
                        new
                        {
                            Id = 25,
                            Name = "StockTransactionStatus_s"
                        },
                        new
                        {
                            Id = 30,
                            EntityKey = "currencies",
                            Name = "Currency_s"
                        },
                        new
                        {
                            Id = 31,
                            Name = "SupplierType_s"
                        },
                        new
                        {
                            Id = 32,
                            EntityKey = "suppliers",
                            Name = "Supplier_cs"
                        },
                        new
                        {
                            Id = 33,
                            EntityKey = "companies",
                            Name = "Company_cs"
                        },
                        new
                        {
                            Id = 34,
                            EntityKey = "currency-exchange-rates",
                            Name = "CurrencyExchangeRate_cs"
                        });
                });

            modelBuilder.Entity("MerkERP.Core.Models.UOMConversionFactor_cs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InternalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<int?>("UOMConversionGroupId")
                        .HasColumnType("int");

                    b.Property<long>("UOMFromId")
                        .HasColumnType("bigint");

                    b.Property<long>("UOMToId")
                        .HasColumnType("bigint");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("InsertedBy");

                    b.HasIndex("UOMConversionGroupId");

                    b.HasIndex("UOMFromId");

                    b.HasIndex("UOMToId");

                    b.ToTable("UOMConversionFactor_cs");
                });

            modelBuilder.Entity("MerkERP.Core.Models.UOMConversionGroup_cs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InternalCode")
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<string>("Name_AR")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("InsertedBy");

                    b.ToTable("UOMConversionGroup_cs");
                });

            modelBuilder.Entity("MerkERP.Core.Models.UOM_cs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InternalCode")
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<bool>("MustBeWholeNumber")
                        .HasColumnType("bit");

                    b.Property<string>("Name_AR")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("InsertedBy");

                    b.ToTable("UOM_cs");
                });

            modelBuilder.Entity("MerkERP.Core.Models.UserType_s", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name_AR")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("UserType_s");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name_AR = "روت",
                            Name_EN = "Root"
                        },
                        new
                        {
                            Id = 2L,
                            Name_AR = "مدير ميرك",
                            Name_EN = "Merk Admin"
                        },
                        new
                        {
                            Id = 3L,
                            Name_AR = "مدير",
                            Name_EN = "Admin"
                        },
                        new
                        {
                            Id = 4L,
                            Name_AR = "مستخدم عادي",
                            Name_EN = "Regular User"
                        });
                });

            modelBuilder.Entity("MerkERP.Core.Models.User_cs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name_AR")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("UserTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InsertedBy");

                    b.HasIndex("UserTypeId");

                    b.ToTable("User_cs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsActive = true,
                            Login = "admin",
                            Name_AR = "مدير",
                            Name_EN = "Admin",
                            Password = "admin",
                            UserTypeId = 2L
                        });
                });

            modelBuilder.Entity("MerkERP.Core.Models.WareHouseCategory_cs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InternalCode")
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name_AR")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("WareHouseTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InsertedBy");

                    b.HasIndex("WareHouseTypeId");

                    b.ToTable("WareHouseCategory_cs");
                });

            modelBuilder.Entity("MerkERP.Core.Models.WareHouseType_s", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name_AR")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("WareHouseType_s");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name_AR = "مستودعات الأدوية",
                            Name_EN = "Pharmaceutical Warehouses"
                        },
                        new
                        {
                            Id = 2L,
                            Name_AR = "مستودعات المستهلكات ومعدات الوقاية الشخصية",
                            Name_EN = "Consumables & PPE Warehouses"
                        },
                        new
                        {
                            Id = 3L,
                            Name_AR = "مستودعات الأجهزة والمعدات الطبية",
                            Name_EN = "Medical Device & Equipment Warehouses"
                        },
                        new
                        {
                            Id = 4L,
                            Name_AR = "مستودعات العمليات الجراحية المعقمة",
                            Name_EN = "Sterile Surgical Warehouses"
                        });
                });

            modelBuilder.Entity("MerkERP.Core.Models.WareHouse_cs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InternalCode")
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<bool>("IsParent")
                        .HasColumnType("bit");

                    b.Property<string>("Name_AR")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("ParentWarehouseId")
                        .HasColumnType("bigint");

                    b.Property<long?>("WareHouseCategoryId")
                        .HasColumnType("bigint");

                    b.Property<long?>("WareHouseTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InsertedBy");

                    b.HasIndex("ParentWarehouseId");

                    b.HasIndex("WareHouseCategoryId");

                    b.HasIndex("WareHouseTypeId");

                    b.ToTable("WareHouse_cs");
                });

            modelBuilder.Entity("MerkERP.Core.Models.Branch_cs", b =>
                {
                    b.HasOne("MerkERP.Core.Models.User_cs", null)
                        .WithMany()
                        .HasForeignKey("InsertedBy")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("MerkERP.Core.Models.Company_cs", b =>
                {
                    b.HasOne("MerkERP.Core.Models.Currency_s", "DefaultCurrency")
                        .WithMany()
                        .HasForeignKey("DefaultCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MerkERP.Core.Models.User_cs", null)
                        .WithMany()
                        .HasForeignKey("InsertedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DefaultCurrency");
                });

            modelBuilder.Entity("MerkERP.Core.Models.CurrencyExchangeRate_cs", b =>
                {
                    b.HasOne("MerkERP.Core.Models.Currency_s", "FromCurrency")
                        .WithMany()
                        .HasForeignKey("FromCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MerkERP.Core.Models.User_cs", null)
                        .WithMany()
                        .HasForeignKey("InsertedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MerkERP.Core.Models.Currency_s", "ToCurrency")
                        .WithMany()
                        .HasForeignKey("ToCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromCurrency");

                    b.Navigation("ToCurrency");
                });

            modelBuilder.Entity("MerkERP.Core.Models.ItemGroup_cs", b =>
                {
                    b.HasOne("MerkERP.Core.Models.User_cs", null)
                        .WithMany()
                        .HasForeignKey("InsertedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MerkERP.Core.Models.ItemGroup_cs", "ParentItemGroup")
                        .WithMany("Children")
                        .HasForeignKey("ParentItemGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentItemGroup");
                });

            modelBuilder.Entity("MerkERP.Core.Models.ItemType_s", b =>
                {
                    b.HasOne("MerkERP.Core.Models.User_cs", null)
                        .WithMany()
                        .HasForeignKey("InsertedBy")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("MerkERP.Core.Models.ItemUOMConversion_cs", b =>
                {
                    b.HasOne("MerkERP.Core.Models.User_cs", null)
                        .WithMany()
                        .HasForeignKey("InsertedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MerkERP.Core.Models.Item_cs", "Item")
                        .WithMany("UOMConversions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MerkERP.Core.Models.UOM_cs", "UOM")
                        .WithMany("Conversions")
                        .HasForeignKey("UOMId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("UOM");
                });

            modelBuilder.Entity("MerkERP.Core.Models.Item_UOM_Barcode_cs", b =>
                {
                    b.HasOne("MerkERP.Core.Models.BarcodeType_s", "BarcodeType")
                        .WithMany()
                        .HasForeignKey("BarcodeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MerkERP.Core.Models.Item_cs", "Item")
                        .WithMany("Barcodes")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MerkERP.Core.Models.UOM_cs", "UOM")
                        .WithMany()
                        .HasForeignKey("UOMId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BarcodeType");

                    b.Navigation("Item");

                    b.Navigation("UOM");
                });

            modelBuilder.Entity("MerkERP.Core.Models.Item_cs", b =>
                {
                    b.HasOne("MerkERP.Core.Models.UOM_cs", "DefaultPurchaseUOM")
                        .WithMany()
                        .HasForeignKey("DefaultPurchaseUOMId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MerkERP.Core.Models.UOM_cs", "DefaultSellingUOM")
                        .WithMany()
                        .HasForeignKey("DefaultSellingUOMId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MerkERP.Core.Models.UOM_cs", "DefaultUOM")
                        .WithMany("DefaultForItems")
                        .HasForeignKey("DefaultUOMId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MerkERP.Core.Models.WareHouse_cs", "DefaultWarehouse")
                        .WithMany()
                        .HasForeignKey("DefaultWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MerkERP.Core.Models.User_cs", null)
                        .WithMany()
                        .HasForeignKey("InsertedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MerkERP.Core.Models.InventoryValidationMethod_s", "InventoryValidationMethod")
                        .WithMany()
                        .HasForeignKey("InventoryValidationMethodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MerkERP.Core.Models.ItemGroup_cs", "ItemGroup")
                        .WithMany("Items")
                        .HasForeignKey("ItemGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MerkERP.Core.Models.ItemType_s", "ItemType")
                        .WithMany("Items")
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefaultPurchaseUOM");

                    b.Navigation("DefaultSellingUOM");

                    b.Navigation("DefaultUOM");

                    b.Navigation("DefaultWarehouse");

                    b.Navigation("InventoryValidationMethod");

                    b.Navigation("ItemGroup");

                    b.Navigation("ItemType");
                });

            modelBuilder.Entity("MerkERP.Core.Models.StockLedgerTransaction", b =>
                {
                    b.HasOne("MerkERP.Core.Models.User_cs", null)
                        .WithMany()
                        .HasForeignKey("InsertedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MerkERP.Core.Models.Item_cs", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MerkERP.Core.Models.StockTransactionType_s", "StockTransactionType")
                        .WithMany()
                        .HasForeignKey("StockTransactionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MerkERP.Core.Models.WareHouse_cs", "WareHouse")
                        .WithMany()
                        .HasForeignKey("WareHouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("StockTransactionType");

                    b.Navigation("WareHouse");
                });

            modelBuilder.Entity("MerkERP.Core.Models.StockReconciliationTransaction", b =>
                {
                    b.HasOne("MerkERP.Core.Models.User_cs", null)
                        .WithMany()
                        .HasForeignKey("InsertedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MerkERP.Core.Models.WareHouse_cs", "SetWarehouse")
                        .WithMany()
                        .HasForeignKey("SetWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MerkERP.Core.Models.StockTransactionStatus_s", "StockTransactionStatus")
                        .WithMany()
                        .HasForeignKey("StockTransactionStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MerkERP.Core.Models.StockTransactionType_s", "StockTransactionType")
                        .WithMany()
                        .HasForeignKey("StockTransactionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SetWarehouse");

                    b.Navigation("StockTransactionStatus");

                    b.Navigation("StockTransactionType");
                });

            modelBuilder.Entity("MerkERP.Core.Models.StockReconciliationTransactionDate", b =>
                {
                    b.HasOne("MerkERP.Core.Models.User_cs", null)
                        .WithMany()
                        .HasForeignKey("InsertedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MerkERP.Core.Models.StockReconciliationTransaction", "StockReconciliationTransaction")
                        .WithMany()
                        .HasForeignKey("StockReconciliationTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MerkERP.Core.Models.StockTransactionStatus_s", "StockTransactionStatus")
                        .WithMany()
                        .HasForeignKey("StockTransactionStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MerkERP.Core.Models.StockTransactionType_s", "StockTransactionType")
                        .WithMany()
                        .HasForeignKey("StockTransactionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StockReconciliationTransaction");

                    b.Navigation("StockTransactionStatus");

                    b.Navigation("StockTransactionType");
                });

            modelBuilder.Entity("MerkERP.Core.Models.StockReconciliationTransactionDetail", b =>
                {
                    b.HasOne("MerkERP.Core.Models.User_cs", null)
                        .WithMany()
                        .HasForeignKey("InsertedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MerkERP.Core.Models.Item_cs", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MerkERP.Core.Models.StockReconciliationTransaction", "StockReconciliationTransaction")
                        .WithMany("Details")
                        .HasForeignKey("StockReconciliationTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MerkERP.Core.Models.UOM_cs", "UOM")
                        .WithMany()
                        .HasForeignKey("UOMId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MerkERP.Core.Models.WareHouse_cs", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("StockReconciliationTransaction");

                    b.Navigation("UOM");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("MerkERP.Core.Models.Supplier_cs", b =>
                {
                    b.HasOne("MerkERP.Core.Models.Currency_s", "DefaultCurrency")
                        .WithMany()
                        .HasForeignKey("DefaultCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MerkERP.Core.Models.User_cs", null)
                        .WithMany()
                        .HasForeignKey("InsertedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MerkERP.Core.Models.SupplierType_s", "SupplierType")
                        .WithMany()
                        .HasForeignKey("SupplierTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DefaultCurrency");

                    b.Navigation("SupplierType");
                });

            modelBuilder.Entity("MerkERP.Core.Models.TableMetaData", b =>
                {
                    b.HasOne("MerkERP.Core.Models.TableMetaData_DataType_s", "DataType")
                        .WithMany()
                        .HasForeignKey("DataTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MerkERP.Core.Models.TableMetaData_FilterType_s", "FilterType")
                        .WithMany()
                        .HasForeignKey("FilterTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MerkERP.Core.Models.TableMetaData_RenderAs_s", "RenderAs")
                        .WithMany()
                        .HasForeignKey("RenderAsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MerkERP.Core.Models.TableName_s", "TableName")
                        .WithMany()
                        .HasForeignKey("TableNameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DataType");

                    b.Navigation("FilterType");

                    b.Navigation("RenderAs");

                    b.Navigation("TableName");
                });

            modelBuilder.Entity("MerkERP.Core.Models.UOMConversionFactor_cs", b =>
                {
                    b.HasOne("MerkERP.Core.Models.User_cs", null)
                        .WithMany()
                        .HasForeignKey("InsertedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MerkERP.Core.Models.UOMConversionGroup_cs", "UOMConversionGroup")
                        .WithMany()
                        .HasForeignKey("UOMConversionGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MerkERP.Core.Models.UOM_cs", "UOMFrom")
                        .WithMany()
                        .HasForeignKey("UOMFromId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MerkERP.Core.Models.UOM_cs", "UOMTo")
                        .WithMany()
                        .HasForeignKey("UOMToId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UOMConversionGroup");

                    b.Navigation("UOMFrom");

                    b.Navigation("UOMTo");
                });

            modelBuilder.Entity("MerkERP.Core.Models.UOMConversionGroup_cs", b =>
                {
                    b.HasOne("MerkERP.Core.Models.User_cs", null)
                        .WithMany()
                        .HasForeignKey("InsertedBy")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("MerkERP.Core.Models.UOM_cs", b =>
                {
                    b.HasOne("MerkERP.Core.Models.User_cs", null)
                        .WithMany()
                        .HasForeignKey("InsertedBy")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("MerkERP.Core.Models.User_cs", b =>
                {
                    b.HasOne("MerkERP.Core.Models.User_cs", null)
                        .WithMany()
                        .HasForeignKey("InsertedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MerkERP.Core.Models.UserType_s", "UserType")
                        .WithMany()
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("MerkERP.Core.Models.WareHouseCategory_cs", b =>
                {
                    b.HasOne("MerkERP.Core.Models.User_cs", null)
                        .WithMany()
                        .HasForeignKey("InsertedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MerkERP.Core.Models.WareHouseType_s", "WareHouseType")
                        .WithMany()
                        .HasForeignKey("WareHouseTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("WareHouseType");
                });

            modelBuilder.Entity("MerkERP.Core.Models.WareHouse_cs", b =>
                {
                    b.HasOne("MerkERP.Core.Models.User_cs", null)
                        .WithMany()
                        .HasForeignKey("InsertedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MerkERP.Core.Models.WareHouse_cs", "ParentWarehouse")
                        .WithMany("Children")
                        .HasForeignKey("ParentWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MerkERP.Core.Models.WareHouseCategory_cs", "WareHouseCategory")
                        .WithMany()
                        .HasForeignKey("WareHouseCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MerkERP.Core.Models.WareHouseType_s", "WareHouseType")
                        .WithMany()
                        .HasForeignKey("WareHouseTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentWarehouse");

                    b.Navigation("WareHouseCategory");

                    b.Navigation("WareHouseType");
                });

            modelBuilder.Entity("MerkERP.Core.Models.ItemGroup_cs", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("MerkERP.Core.Models.ItemType_s", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MerkERP.Core.Models.Item_cs", b =>
                {
                    b.Navigation("Barcodes");

                    b.Navigation("UOMConversions");
                });

            modelBuilder.Entity("MerkERP.Core.Models.StockReconciliationTransaction", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("MerkERP.Core.Models.UOM_cs", b =>
                {
                    b.Navigation("Conversions");

                    b.Navigation("DefaultForItems");
                });

            modelBuilder.Entity("MerkERP.Core.Models.WareHouse_cs", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
