// <auto-generated />
using System;
using MerkERP.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MerkERP.DAL.Migrations
{
    [DbContext(typeof(MerkDbContext))]
    [Migration("20260605211059_AddInternalCodeToUOMConversionGroup")]
    partial class AddInternalCodeToUOMConversionGroup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MerkERP.Core.Models.ItemGroup_cs", b =>
                {
                    b.Property<long>("ItemGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ItemGroupId"));

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGroup")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ParentItemGroupId")
                        .HasColumnType("bigint");

                    b.HasKey("ItemGroupId");

                    b.HasIndex("ParentItemGroupId");

                    b.ToTable("ItemGroup_cs");
                });

            modelBuilder.Entity("MerkERP.Core.Models.ItemType_s", b =>
                {
                    b.Property<long>("ItemTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ItemTypeId"));

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemTypeId");

                    b.ToTable("ItemType_s");

                    b.HasData(
                        new
                        {
                            ItemTypeId = 1L,
                            IsActive = true,
                            IsFavorite = false,
                            Name = "Stock Item"
                        },
                        new
                        {
                            ItemTypeId = 2L,
                            IsActive = true,
                            IsFavorite = false,
                            Name = "Service"
                        },
                        new
                        {
                            ItemTypeId = 3L,
                            IsActive = true,
                            IsFavorite = false,
                            Name = "Non-Stock Item"
                        });
                });

            modelBuilder.Entity("MerkERP.Core.Models.ItemUOMConversion_cs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ConversionFactor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("UOMId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UOMId");

                    b.ToTable("ItemUOMConversion_cs");
                });

            modelBuilder.Entity("MerkERP.Core.Models.Item_cs", b =>
                {
                    b.Property<long>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ItemId"));

                    b.Property<long>("DefaultUOMId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasBatch")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSerial")
                        .HasColumnType("bit");

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("ItemGroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ItemTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("ItemId");

                    b.HasIndex("DefaultUOMId");

                    b.HasIndex("ItemCode")
                        .IsUnique();

                    b.HasIndex("ItemGroupId");

                    b.HasIndex("ItemTypeId");

                    b.ToTable("Item_cs");
                });

            modelBuilder.Entity("MerkERP.Core.Models.StockLedgerTransaction", b =>
                {
                    b.Property<long>("SLTId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SLTId"));

                    b.Property<decimal>("ActualQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BatchNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("PostingDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("PostingTime")
                        .HasColumnType("time");

                    b.Property<decimal>("QtyAfterTransaction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StockValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValuationRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VoucherNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoucherType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("WarehouseId")
                        .HasColumnType("bigint");

                    b.HasKey("SLTId");

                    b.HasIndex("ItemId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("StockLedgerTransaction");
                });

            modelBuilder.Entity("MerkERP.Core.Models.UOMConversionFactor_cs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<long>("UOMFromId")
                        .HasColumnType("bigint");

                    b.Property<long>("UOMToId")
                        .HasColumnType("bigint");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UOMFromId");

                    b.HasIndex("UOMToId");

                    b.ToTable("UOMConversionFactor_cs");
                });

            modelBuilder.Entity("MerkERP.Core.Models.UOMConversionGroup_cs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InternalCode")
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<string>("Name_AR")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("UOMConversionGroup_cs");
                });

            modelBuilder.Entity("MerkERP.Core.Models.UOM_cs", b =>
                {
                    b.Property<long>("UOMId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UOMId"));

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<bool>("MustBeWholeNumber")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UOMId");

                    b.ToTable("UOM_cs");
                });

            modelBuilder.Entity("MerkERP.Core.Models.WareHouse_cs", b =>
                {
                    b.Property<long>("WarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("WarehouseId"));

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGroup")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ParentWarehouseId")
                        .HasColumnType("bigint");

                    b.HasKey("WarehouseId");

                    b.HasIndex("ParentWarehouseId");

                    b.ToTable("WareHouse_cs");
                });

            modelBuilder.Entity("MerkERP.Core.Models.WarehouseTransaction", b =>
                {
                    b.Property<long>("BinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BinId"));

                    b.Property<decimal>("ActualQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("OrderedQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ReservedQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValuationRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("WarehouseId")
                        .HasColumnType("bigint");

                    b.HasKey("BinId");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("ItemId", "WarehouseId")
                        .IsUnique();

                    b.ToTable("WarehouseTransaction");
                });

            modelBuilder.Entity("MerkERP.Core.Models.ItemGroup_cs", b =>
                {
                    b.HasOne("MerkERP.Core.Models.ItemGroup_cs", "ParentItemGroup")
                        .WithMany("Children")
                        .HasForeignKey("ParentItemGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentItemGroup");
                });

            modelBuilder.Entity("MerkERP.Core.Models.ItemUOMConversion_cs", b =>
                {
                    b.HasOne("MerkERP.Core.Models.Item_cs", "Item")
                        .WithMany("UOMConversions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MerkERP.Core.Models.UOM_cs", "UOM")
                        .WithMany("Conversions")
                        .HasForeignKey("UOMId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("UOM");
                });

            modelBuilder.Entity("MerkERP.Core.Models.Item_cs", b =>
                {
                    b.HasOne("MerkERP.Core.Models.UOM_cs", "DefaultUOM")
                        .WithMany("DefaultForItems")
                        .HasForeignKey("DefaultUOMId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MerkERP.Core.Models.ItemGroup_cs", "ItemGroup")
                        .WithMany("Items")
                        .HasForeignKey("ItemGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MerkERP.Core.Models.ItemType_s", "ItemType")
                        .WithMany("Items")
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefaultUOM");

                    b.Navigation("ItemGroup");

                    b.Navigation("ItemType");
                });

            modelBuilder.Entity("MerkERP.Core.Models.StockLedgerTransaction", b =>
                {
                    b.HasOne("MerkERP.Core.Models.Item_cs", "Item")
                        .WithMany("StockLedgerTransactions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MerkERP.Core.Models.WareHouse_cs", "Warehouse")
                        .WithMany("StockLedgerTransactions")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("MerkERP.Core.Models.UOMConversionFactor_cs", b =>
                {
                    b.HasOne("MerkERP.Core.Models.UOM_cs", "UOMFrom")
                        .WithMany()
                        .HasForeignKey("UOMFromId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MerkERP.Core.Models.UOM_cs", "UOMTo")
                        .WithMany()
                        .HasForeignKey("UOMToId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UOMFrom");

                    b.Navigation("UOMTo");
                });

            modelBuilder.Entity("MerkERP.Core.Models.WareHouse_cs", b =>
                {
                    b.HasOne("MerkERP.Core.Models.WareHouse_cs", "ParentWarehouse")
                        .WithMany("Children")
                        .HasForeignKey("ParentWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentWarehouse");
                });

            modelBuilder.Entity("MerkERP.Core.Models.WarehouseTransaction", b =>
                {
                    b.HasOne("MerkERP.Core.Models.Item_cs", "Item")
                        .WithMany("WarehouseTransactions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MerkERP.Core.Models.WareHouse_cs", "Warehouse")
                        .WithMany("Transactions")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("MerkERP.Core.Models.ItemGroup_cs", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("MerkERP.Core.Models.ItemType_s", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MerkERP.Core.Models.Item_cs", b =>
                {
                    b.Navigation("StockLedgerTransactions");

                    b.Navigation("UOMConversions");

                    b.Navigation("WarehouseTransactions");
                });

            modelBuilder.Entity("MerkERP.Core.Models.UOM_cs", b =>
                {
                    b.Navigation("Conversions");

                    b.Navigation("DefaultForItems");
                });

            modelBuilder.Entity("MerkERP.Core.Models.WareHouse_cs", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("StockLedgerTransactions");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
