// <auto-generated />
using System;
using MerkERP.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MerkERP.DAL.Migrations
{
    [DbContext(typeof(MerkDbContext))]
    [Migration("20260612185957_AddWareHouseTypeIdToCategory")]
    partial class AddWareHouseTypeIdToCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MerkERP.Core.Models.BarcodeType_s", b =>
                {
                    b.Property<long>("BarcodeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BarcodeTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BarcodeTypeId");

                    b.ToTable("BarcodeType_s");

                    b.HasData(
                        new
                        {
                            BarcodeTypeId = 1L,
                            Name = "EAN-13"
                        },
                        new
                        {
                            BarcodeTypeId = 2L,
                            Name = "EAN-8"
                        },
                        new
                        {
                            BarcodeTypeId = 3L,
                            Name = "UPC-A"
                        },
                        new
                        {
                            BarcodeTypeId = 4L,
                            Name = "UPC-E"
                        },
                        new
                        {
                            BarcodeTypeId = 5L,
                            Name = "Code 39"
                        },
                        new
                        {
                            BarcodeTypeId = 6L,
                            Name = "Code 128"
                        },
                        new
                        {
                            BarcodeTypeId = 7L,
                            Name = "ITF-14"
                        },
                        new
                        {
                            BarcodeTypeId = 8L,
                            Name = "GS1-128"
                        },
                        new
                        {
                            BarcodeTypeId = 9L,
                            Name = "QR Code"
                        },
                        new
                        {
                            BarcodeTypeId = 10L,
                            Name = "Data Matrix"
                        },
                        new
                        {
                            BarcodeTypeId = 11L,
                            Name = "Custom"
                        });
                });

            modelBuilder.Entity("MerkERP.Core.Models.Branch_cs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name_AR")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Branch_cs");
                });

            modelBuilder.Entity("MerkERP.Core.Models.InventoryValidationMethod_s", b =>
                {
                    b.Property<long>("InventoryValidationMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InventoryValidationMethodId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InventoryValidationMethodId");

                    b.ToTable("InventoryValidationMethod_s");

                    b.HasData(
                        new
                        {
                            InventoryValidationMethodId = 1L,
                            Name = "FIFO"
                        },
                        new
                        {
                            InventoryValidationMethodId = 2L,
                            Name = "LIFO"
                        },
                        new
                        {
                            InventoryValidationMethodId = 3L,
                            Name = "Moving Average"
                        });
                });

            modelBuilder.Entity("MerkERP.Core.Models.ItemGroup_cs", b =>
                {
                    b.Property<long>("ItemGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ItemGroupId"));

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InternalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<string>("Name_AR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ParentItemGroupId")
                        .HasColumnType("bigint");

                    b.HasKey("ItemGroupId");

                    b.HasIndex("ParentItemGroupId");

                    b.ToTable("ItemGroup_cs");
                });

            modelBuilder.Entity("MerkERP.Core.Models.ItemType_s", b =>
                {
                    b.Property<long>("ItemTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ItemTypeId"));

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemTypeId");

                    b.ToTable("ItemType_s");

                    b.HasData(
                        new
                        {
                            ItemTypeId = 1L,
                            IsActive = true,
                            IsFavorite = false,
                            Name = "Stock Item"
                        },
                        new
                        {
                            ItemTypeId = 2L,
                            IsActive = true,
                            IsFavorite = false,
                            Name = "Service"
                        },
                        new
                        {
                            ItemTypeId = 3L,
                            IsActive = true,
                            IsFavorite = false,
                            Name = "Non-Stock Item"
                        });
                });

            modelBuilder.Entity("MerkERP.Core.Models.ItemUOMConversion_cs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ConversionFactor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("UOMId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UOMId");

                    b.ToTable("ItemUOMConversion_cs");
                });

            modelBuilder.Entity("MerkERP.Core.Models.Item_UOM_Barcode_cs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("BarcodeTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("UOMId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BarcodeTypeId");

                    b.HasIndex("ItemId");

                    b.HasIndex("UOMId");

                    b.ToTable("Item_UOM_Barcode_cs");
                });

            modelBuilder.Entity("MerkERP.Core.Models.Item_cs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AcceptSelling")
                        .HasColumnType("bit");

                    b.Property<long?>("DefaultPurchaseUOMId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DefaultSellingUOMId")
                        .HasColumnType("bigint");

                    b.Property<long>("DefaultUOMId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DefaultWarehouseId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InternalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("InventoryValidationMethodId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<long>("ItemGroupId")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemTypeId")
                        .HasColumnType("bigint");

                    b.Property<int?>("MinOrderQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Name_AR")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("OpeningStock")
                        .HasColumnType("bigint");

                    b.Property<long?>("SafetyStock")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DefaultPurchaseUOMId");

                    b.HasIndex("DefaultSellingUOMId");

                    b.HasIndex("DefaultUOMId");

                    b.HasIndex("DefaultWarehouseId");

                    b.HasIndex("InternalCode")
                        .IsUnique();

                    b.HasIndex("InventoryValidationMethodId");

                    b.HasIndex("ItemGroupId");

                    b.HasIndex("ItemTypeId");

                    b.ToTable("Item_cs");
                });

            modelBuilder.Entity("MerkERP.Core.Models.StockLedgerTransaction", b =>
                {
                    b.Property<long>("SLTId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SLTId"));

                    b.Property<decimal>("ActualQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BatchNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("PostingDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("PostingTime")
                        .HasColumnType("time");

                    b.Property<decimal>("QtyAfterTransaction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StockValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValuationRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VoucherNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoucherType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("WarehouseId")
                        .HasColumnType("bigint");

                    b.HasKey("SLTId");

                    b.HasIndex("ItemId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("StockLedgerTransaction");
                });

            modelBuilder.Entity("MerkERP.Core.Models.TableMetaData", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("ColumnOrder")
                        .HasColumnType("int");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EntityProperty")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FilterType")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ForeignKeyProperty")
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsFilterable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSortable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LabelAR")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LabelEN")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MinWidth")
                        .HasColumnType("int");

                    b.Property<string>("RenderAs")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TableNameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TableNameId", "Key")
                        .IsUnique();

                    b.ToTable("TableMetaData");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ColumnOrder = 1,
                            DataType = "string",
                            EntityProperty = "InternalCode",
                            FilterType = "text",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "internalCode",
                            LabelAR = "الكود",
                            LabelEN = "Code",
                            RenderAs = "text",
                            TableNameId = 4
                        },
                        new
                        {
                            Id = 2L,
                            ColumnOrder = 2,
                            DataType = "string",
                            EntityProperty = "Name_AR",
                            FilterType = "text",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "name_AR",
                            LabelAR = "الاسم (AR)",
                            LabelEN = "Name (AR)",
                            RenderAs = "text",
                            TableNameId = 4
                        },
                        new
                        {
                            Id = 3L,
                            ColumnOrder = 3,
                            DataType = "string",
                            EntityProperty = "Name_EN",
                            FilterType = "text",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "name_EN",
                            LabelAR = "الاسم (EN)",
                            LabelEN = "Name (EN)",
                            RenderAs = "text",
                            TableNameId = 4
                        },
                        new
                        {
                            Id = 4L,
                            ColumnOrder = 4,
                            DataType = "string",
                            EntityProperty = "ItemGroup",
                            FilterType = "select",
                            ForeignKeyProperty = "ItemGroupId",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "itemGroup",
                            LabelAR = "مجموعة الصنف",
                            LabelEN = "Item Group",
                            RenderAs = "text",
                            TableNameId = 4
                        },
                        new
                        {
                            Id = 5L,
                            ColumnOrder = 5,
                            DataType = "string",
                            EntityProperty = "ItemType",
                            FilterType = "select",
                            ForeignKeyProperty = "ItemTypeId",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "itemType",
                            LabelAR = "نوع الصنف",
                            LabelEN = "Item Type",
                            RenderAs = "text",
                            TableNameId = 4
                        },
                        new
                        {
                            Id = 6L,
                            ColumnOrder = 6,
                            DataType = "string",
                            EntityProperty = "DefaultUOM",
                            FilterType = "select",
                            ForeignKeyProperty = "DefaultUOMId",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "defaultUOM",
                            LabelAR = "وحدة القياس",
                            LabelEN = "Default UOM",
                            RenderAs = "text",
                            TableNameId = 4
                        },
                        new
                        {
                            Id = 7L,
                            ColumnOrder = 7,
                            DataType = "boolean",
                            EntityProperty = "IsActive",
                            FilterType = "boolean",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "isActive",
                            LabelAR = "نشط",
                            LabelEN = "Active",
                            RenderAs = "badge",
                            TableNameId = 4
                        },
                        new
                        {
                            Id = 8L,
                            ColumnOrder = 1,
                            DataType = "string",
                            EntityProperty = "InternalCode",
                            FilterType = "text",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "internalCode",
                            LabelAR = "الكود الداخلي",
                            LabelEN = "Internal Code",
                            RenderAs = "text",
                            TableNameId = 6
                        },
                        new
                        {
                            Id = 9L,
                            ColumnOrder = 2,
                            DataType = "string",
                            EntityProperty = "Name_AR",
                            FilterType = "text",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "name_AR",
                            LabelAR = "الاسم (AR)",
                            LabelEN = "Name (AR)",
                            RenderAs = "text",
                            TableNameId = 6
                        },
                        new
                        {
                            Id = 10L,
                            ColumnOrder = 3,
                            DataType = "string",
                            EntityProperty = "Name_EN",
                            FilterType = "text",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "name_EN",
                            LabelAR = "الاسم (EN)",
                            LabelEN = "Name (EN)",
                            RenderAs = "text",
                            TableNameId = 6
                        },
                        new
                        {
                            Id = 11L,
                            ColumnOrder = 4,
                            DataType = "string",
                            EntityProperty = "ParentItemGroup",
                            FilterType = "select",
                            ForeignKeyProperty = "ParentItemGroupId",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "parentItemGroup",
                            LabelAR = "المجموعة الأصل",
                            LabelEN = "Parent Group",
                            RenderAs = "text",
                            TableNameId = 6
                        },
                        new
                        {
                            Id = 12L,
                            ColumnOrder = 5,
                            DataType = "boolean",
                            EntityProperty = "IsMain",
                            FilterType = "boolean",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "isMain",
                            LabelAR = "أصل",
                            LabelEN = "Is Main",
                            RenderAs = "badge",
                            TableNameId = 6
                        },
                        new
                        {
                            Id = 13L,
                            ColumnOrder = 6,
                            DataType = "boolean",
                            EntityProperty = "IsActive",
                            FilterType = "boolean",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "isActive",
                            LabelAR = "نشط",
                            LabelEN = "Active",
                            RenderAs = "badge",
                            TableNameId = 6
                        },
                        new
                        {
                            Id = 14L,
                            ColumnOrder = 1,
                            DataType = "string",
                            EntityProperty = "InternalCode",
                            FilterType = "text",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "internalCode",
                            LabelAR = "الكود الداخلي",
                            LabelEN = "Internal Code",
                            RenderAs = "text",
                            TableNameId = 11
                        },
                        new
                        {
                            Id = 15L,
                            ColumnOrder = 2,
                            DataType = "string",
                            EntityProperty = "Name_AR",
                            FilterType = "text",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "name_AR",
                            LabelAR = "الاسم (AR)",
                            LabelEN = "Name (AR)",
                            RenderAs = "text",
                            TableNameId = 11
                        },
                        new
                        {
                            Id = 16L,
                            ColumnOrder = 3,
                            DataType = "string",
                            EntityProperty = "Name_EN",
                            FilterType = "text",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "name_EN",
                            LabelAR = "الاسم (EN)",
                            LabelEN = "Name (EN)",
                            RenderAs = "text",
                            TableNameId = 11
                        },
                        new
                        {
                            Id = 17L,
                            ColumnOrder = 4,
                            DataType = "boolean",
                            EntityProperty = "MustBeWholeNumber",
                            FilterType = "boolean",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "mustBeWholeNumber",
                            LabelAR = "يجب أن يكون صحيحاً",
                            LabelEN = "Must Be Whole No.",
                            RenderAs = "yesno",
                            TableNameId = 11
                        },
                        new
                        {
                            Id = 18L,
                            ColumnOrder = 5,
                            DataType = "boolean",
                            EntityProperty = "IsActive",
                            FilterType = "boolean",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "isActive",
                            LabelAR = "نشط",
                            LabelEN = "Active",
                            RenderAs = "badge",
                            TableNameId = 11
                        },
                        new
                        {
                            Id = 19L,
                            ColumnOrder = 1,
                            DataType = "string",
                            EntityProperty = "InternalCode",
                            FilterType = "text",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "internalCode",
                            LabelAR = "الكود الداخلي",
                            LabelEN = "Internal Code",
                            RenderAs = "text",
                            TableNameId = 13
                        },
                        new
                        {
                            Id = 20L,
                            ColumnOrder = 2,
                            DataType = "string",
                            EntityProperty = "Name_AR",
                            FilterType = "text",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "name_AR",
                            LabelAR = "الاسم (AR)",
                            LabelEN = "Name (AR)",
                            RenderAs = "text",
                            TableNameId = 13
                        },
                        new
                        {
                            Id = 21L,
                            ColumnOrder = 3,
                            DataType = "string",
                            EntityProperty = "Name_EN",
                            FilterType = "text",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "name_EN",
                            LabelAR = "الاسم (EN)",
                            LabelEN = "Name (EN)",
                            RenderAs = "text",
                            TableNameId = 13
                        },
                        new
                        {
                            Id = 22L,
                            ColumnOrder = 4,
                            DataType = "boolean",
                            EntityProperty = "IsActive",
                            FilterType = "boolean",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "isActive",
                            LabelAR = "نشط",
                            LabelEN = "Active",
                            RenderAs = "badge",
                            TableNameId = 13
                        },
                        new
                        {
                            Id = 23L,
                            ColumnOrder = 1,
                            DataType = "string",
                            EntityProperty = "InternalCode",
                            FilterType = "text",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "internalCode",
                            LabelAR = "الكود الداخلي",
                            LabelEN = "Internal Code",
                            RenderAs = "text",
                            TableNameId = 12
                        },
                        new
                        {
                            Id = 24L,
                            ColumnOrder = 2,
                            DataType = "string",
                            EntityProperty = "UOMFrom",
                            FilterType = "select",
                            ForeignKeyProperty = "UOMFromId",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "uomFrom",
                            LabelAR = "من وحدة القياس",
                            LabelEN = "From UOM",
                            RenderAs = "text",
                            TableNameId = 12
                        },
                        new
                        {
                            Id = 25L,
                            ColumnOrder = 3,
                            DataType = "string",
                            EntityProperty = "UOMTo",
                            FilterType = "select",
                            ForeignKeyProperty = "UOMToId",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "uomTo",
                            LabelAR = "إلى وحدة القياس",
                            LabelEN = "To UOM",
                            RenderAs = "text",
                            TableNameId = 12
                        },
                        new
                        {
                            Id = 26L,
                            ColumnOrder = 4,
                            DataType = "number",
                            EntityProperty = "Value",
                            FilterType = "number",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "value",
                            LabelAR = "معامل التحويل",
                            LabelEN = "Factor",
                            RenderAs = "text",
                            TableNameId = 12
                        },
                        new
                        {
                            Id = 27L,
                            ColumnOrder = 5,
                            DataType = "string",
                            EntityProperty = "UOMConversionGroup",
                            FilterType = "select",
                            ForeignKeyProperty = "UOMConversionGroupId",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "uomConversionGroup",
                            LabelAR = "مجموعة التحويل",
                            LabelEN = "Conversion Group",
                            RenderAs = "text",
                            TableNameId = 12
                        },
                        new
                        {
                            Id = 28L,
                            ColumnOrder = 6,
                            DataType = "boolean",
                            EntityProperty = "IsActive",
                            FilterType = "boolean",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "isActive",
                            LabelAR = "نشط",
                            LabelEN = "Active",
                            RenderAs = "badge",
                            TableNameId = 12
                        },
                        new
                        {
                            Id = 29L,
                            ColumnOrder = 1,
                            DataType = "string",
                            EntityProperty = "InternalCode",
                            FilterType = "text",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "internalCode",
                            LabelAR = "الكود الداخلي",
                            LabelEN = "Internal Code",
                            RenderAs = "text",
                            TableNameId = 14
                        },
                        new
                        {
                            Id = 30L,
                            ColumnOrder = 2,
                            DataType = "string",
                            EntityProperty = "Name_AR",
                            FilterType = "text",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "name_AR",
                            LabelAR = "الاسم (AR)",
                            LabelEN = "Name (AR)",
                            RenderAs = "text",
                            TableNameId = 14
                        },
                        new
                        {
                            Id = 31L,
                            ColumnOrder = 3,
                            DataType = "string",
                            EntityProperty = "Name_EN",
                            FilterType = "text",
                            IsFilterable = true,
                            IsSortable = false,
                            IsVisible = true,
                            Key = "name_EN",
                            LabelAR = "الاسم (EN)",
                            LabelEN = "Name (EN)",
                            RenderAs = "tree",
                            TableNameId = 14
                        },
                        new
                        {
                            Id = 32L,
                            ColumnOrder = 4,
                            DataType = "string",
                            EntityProperty = "WareHouseType",
                            FilterType = "select",
                            ForeignKeyProperty = "WareHouseTypeId",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "wareHouseType",
                            LabelAR = "النوع",
                            LabelEN = "Type",
                            RenderAs = "text",
                            TableNameId = 14
                        },
                        new
                        {
                            Id = 33L,
                            ColumnOrder = 5,
                            DataType = "string",
                            EntityProperty = "WareHouseCategory",
                            FilterType = "select",
                            ForeignKeyProperty = "WareHouseCategoryId",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "wareHouseCategory",
                            LabelAR = "الفئة",
                            LabelEN = "Category",
                            RenderAs = "text",
                            TableNameId = 14
                        },
                        new
                        {
                            Id = 34L,
                            ColumnOrder = 6,
                            DataType = "boolean",
                            EntityProperty = "IsParent",
                            FilterType = "boolean",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "isParent",
                            LabelAR = "أصل",
                            LabelEN = "Is Parent",
                            RenderAs = "badge",
                            TableNameId = 14
                        },
                        new
                        {
                            Id = 35L,
                            ColumnOrder = 7,
                            DataType = "boolean",
                            EntityProperty = "IsActive",
                            FilterType = "boolean",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "isActive",
                            LabelAR = "نشط",
                            LabelEN = "Active",
                            RenderAs = "badge",
                            TableNameId = 14
                        },
                        new
                        {
                            Id = 36L,
                            ColumnOrder = 1,
                            DataType = "string",
                            EntityProperty = "InternalCode",
                            FilterType = "text",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "internalCode",
                            LabelAR = "الكود الداخلي",
                            LabelEN = "Internal Code",
                            RenderAs = "text",
                            TableNameId = 15
                        },
                        new
                        {
                            Id = 37L,
                            ColumnOrder = 2,
                            DataType = "string",
                            EntityProperty = "Name_AR",
                            FilterType = "text",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "name_AR",
                            LabelAR = "الاسم (AR)",
                            LabelEN = "Name (AR)",
                            RenderAs = "text",
                            TableNameId = 15
                        },
                        new
                        {
                            Id = 38L,
                            ColumnOrder = 3,
                            DataType = "string",
                            EntityProperty = "Name_EN",
                            FilterType = "text",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "name_EN",
                            LabelAR = "الاسم (EN)",
                            LabelEN = "Name (EN)",
                            RenderAs = "text",
                            TableNameId = 15
                        },
                        new
                        {
                            Id = 39L,
                            ColumnOrder = 4,
                            DataType = "string",
                            EntityProperty = "Description",
                            FilterType = "text",
                            IsFilterable = true,
                            IsSortable = false,
                            IsVisible = true,
                            Key = "description",
                            LabelAR = "الوصف",
                            LabelEN = "Description",
                            RenderAs = "text",
                            TableNameId = 15
                        },
                        new
                        {
                            Id = 40L,
                            ColumnOrder = 5,
                            DataType = "boolean",
                            EntityProperty = "IsActive",
                            FilterType = "boolean",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "isActive",
                            LabelAR = "نشط",
                            LabelEN = "Active",
                            RenderAs = "badge",
                            TableNameId = 15
                        },
                        new
                        {
                            Id = 41L,
                            ColumnOrder = 1,
                            DataType = "string",
                            EntityProperty = "Name_AR",
                            FilterType = "text",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "name_AR",
                            LabelAR = "الاسم (AR)",
                            LabelEN = "Name (AR)",
                            RenderAs = "text",
                            TableNameId = 2
                        },
                        new
                        {
                            Id = 42L,
                            ColumnOrder = 2,
                            DataType = "string",
                            EntityProperty = "Name_EN",
                            FilterType = "text",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "name_EN",
                            LabelAR = "الاسم (EN)",
                            LabelEN = "Name (EN)",
                            RenderAs = "text",
                            TableNameId = 2
                        },
                        new
                        {
                            Id = 43L,
                            ColumnOrder = 3,
                            DataType = "string",
                            EntityProperty = "Description",
                            FilterType = "text",
                            IsFilterable = true,
                            IsSortable = false,
                            IsVisible = true,
                            Key = "description",
                            LabelAR = "الوصف",
                            LabelEN = "Description",
                            RenderAs = "text",
                            TableNameId = 2
                        },
                        new
                        {
                            Id = 44L,
                            ColumnOrder = 4,
                            DataType = "boolean",
                            EntityProperty = "IsActive",
                            FilterType = "boolean",
                            IsFilterable = true,
                            IsSortable = true,
                            IsVisible = true,
                            Key = "isActive",
                            LabelAR = "نشط",
                            LabelEN = "Active",
                            RenderAs = "badge",
                            TableNameId = 2
                        });
                });

            modelBuilder.Entity("MerkERP.Core.Models.TableName_s", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("EntityKey")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TableName_s");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "BarcodeType_s"
                        },
                        new
                        {
                            Id = 2,
                            EntityKey = "branches",
                            Name = "Branch_cs"
                        },
                        new
                        {
                            Id = 3,
                            Name = "InventoryValidationMethod_s"
                        },
                        new
                        {
                            Id = 4,
                            EntityKey = "items",
                            Name = "Item_cs"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Item_UOM_Barcode_cs"
                        },
                        new
                        {
                            Id = 6,
                            EntityKey = "itemgroups",
                            Name = "ItemGroup_cs"
                        },
                        new
                        {
                            Id = 7,
                            Name = "ItemType_s"
                        },
                        new
                        {
                            Id = 8,
                            Name = "ItemUOMConversion_cs"
                        },
                        new
                        {
                            Id = 9,
                            Name = "StockLedgerTransaction"
                        },
                        new
                        {
                            Id = 10,
                            Name = "TableName_s"
                        },
                        new
                        {
                            Id = 11,
                            EntityKey = "uoms",
                            Name = "UOM_cs"
                        },
                        new
                        {
                            Id = 12,
                            EntityKey = "uomconversionfactors",
                            Name = "UOMConversionFactor_cs"
                        },
                        new
                        {
                            Id = 13,
                            EntityKey = "uomconversiongroups",
                            Name = "UOMConversionGroup_cs"
                        },
                        new
                        {
                            Id = 14,
                            EntityKey = "warehouses",
                            Name = "WareHouse_cs"
                        },
                        new
                        {
                            Id = 15,
                            EntityKey = "warehousecategories",
                            Name = "WareHouseCategory_cs"
                        },
                        new
                        {
                            Id = 16,
                            Name = "WareHouseType_s"
                        },
                        new
                        {
                            Id = 17,
                            Name = "WarehouseTransaction"
                        },
                        new
                        {
                            Id = 18,
                            Name = "TableMetaData"
                        });
                });

            modelBuilder.Entity("MerkERP.Core.Models.UOMConversionFactor_cs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InternalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<int?>("UOMConversionGroupId")
                        .HasColumnType("int");

                    b.Property<long>("UOMFromId")
                        .HasColumnType("bigint");

                    b.Property<long>("UOMToId")
                        .HasColumnType("bigint");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UOMConversionGroupId");

                    b.HasIndex("UOMFromId");

                    b.HasIndex("UOMToId");

                    b.ToTable("UOMConversionFactor_cs");
                });

            modelBuilder.Entity("MerkERP.Core.Models.UOMConversionGroup_cs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InternalCode")
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<string>("Name_AR")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("UOMConversionGroup_cs");
                });

            modelBuilder.Entity("MerkERP.Core.Models.UOM_cs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InternalCode")
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<bool>("MustBeWholeNumber")
                        .HasColumnType("bit");

                    b.Property<string>("Name_AR")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("UOM_cs");
                });

            modelBuilder.Entity("MerkERP.Core.Models.WareHouseCategory_cs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InternalCode")
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name_AR")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("WareHouseTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("WareHouseTypeId");

                    b.ToTable("WareHouseCategory_cs");
                });

            modelBuilder.Entity("MerkERP.Core.Models.WareHouseType_s", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name_AR")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("WareHouseType_s");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name_AR = "مستودعات الأدوية",
                            Name_EN = "Pharmaceutical Warehouses"
                        },
                        new
                        {
                            Id = 2L,
                            Name_AR = "مستودعات المستهلكات ومعدات الوقاية الشخصية",
                            Name_EN = "Consumables & PPE Warehouses"
                        },
                        new
                        {
                            Id = 3L,
                            Name_AR = "مستودعات الأجهزة والمعدات الطبية",
                            Name_EN = "Medical Device & Equipment Warehouses"
                        },
                        new
                        {
                            Id = 4L,
                            Name_AR = "مستودعات العمليات الجراحية المعقمة",
                            Name_EN = "Sterile Surgical Warehouses"
                        });
                });

            modelBuilder.Entity("MerkERP.Core.Models.WareHouse_cs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InternalCode")
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<bool>("IsParent")
                        .HasColumnType("bit");

                    b.Property<string>("Name_AR")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name_EN")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("ParentWarehouseId")
                        .HasColumnType("bigint");

                    b.Property<long?>("WareHouseCategoryId")
                        .HasColumnType("bigint");

                    b.Property<long?>("WareHouseTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentWarehouseId");

                    b.HasIndex("WareHouseCategoryId");

                    b.HasIndex("WareHouseTypeId");

                    b.ToTable("WareHouse_cs");
                });

            modelBuilder.Entity("MerkERP.Core.Models.WarehouseTransaction", b =>
                {
                    b.Property<long>("BinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BinId"));

                    b.Property<decimal>("ActualQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("InsertedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("InsertedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("OrderedQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ReservedQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValuationRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("WarehouseId")
                        .HasColumnType("bigint");

                    b.HasKey("BinId");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("ItemId", "WarehouseId")
                        .IsUnique();

                    b.ToTable("WarehouseTransaction");
                });

            modelBuilder.Entity("MerkERP.Core.Models.ItemGroup_cs", b =>
                {
                    b.HasOne("MerkERP.Core.Models.ItemGroup_cs", "ParentItemGroup")
                        .WithMany("Children")
                        .HasForeignKey("ParentItemGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentItemGroup");
                });

            modelBuilder.Entity("MerkERP.Core.Models.ItemUOMConversion_cs", b =>
                {
                    b.HasOne("MerkERP.Core.Models.Item_cs", "Item")
                        .WithMany("UOMConversions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MerkERP.Core.Models.UOM_cs", "UOM")
                        .WithMany("Conversions")
                        .HasForeignKey("UOMId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("UOM");
                });

            modelBuilder.Entity("MerkERP.Core.Models.Item_UOM_Barcode_cs", b =>
                {
                    b.HasOne("MerkERP.Core.Models.BarcodeType_s", "BarcodeType")
                        .WithMany()
                        .HasForeignKey("BarcodeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MerkERP.Core.Models.Item_cs", "Item")
                        .WithMany("Barcodes")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MerkERP.Core.Models.UOM_cs", "UOM")
                        .WithMany()
                        .HasForeignKey("UOMId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BarcodeType");

                    b.Navigation("Item");

                    b.Navigation("UOM");
                });

            modelBuilder.Entity("MerkERP.Core.Models.Item_cs", b =>
                {
                    b.HasOne("MerkERP.Core.Models.UOM_cs", "DefaultPurchaseUOM")
                        .WithMany()
                        .HasForeignKey("DefaultPurchaseUOMId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MerkERP.Core.Models.UOM_cs", "DefaultSellingUOM")
                        .WithMany()
                        .HasForeignKey("DefaultSellingUOMId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MerkERP.Core.Models.UOM_cs", "DefaultUOM")
                        .WithMany("DefaultForItems")
                        .HasForeignKey("DefaultUOMId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MerkERP.Core.Models.WareHouse_cs", "DefaultWarehouse")
                        .WithMany()
                        .HasForeignKey("DefaultWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MerkERP.Core.Models.InventoryValidationMethod_s", "InventoryValidationMethod")
                        .WithMany()
                        .HasForeignKey("InventoryValidationMethodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MerkERP.Core.Models.ItemGroup_cs", "ItemGroup")
                        .WithMany("Items")
                        .HasForeignKey("ItemGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MerkERP.Core.Models.ItemType_s", "ItemType")
                        .WithMany("Items")
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefaultPurchaseUOM");

                    b.Navigation("DefaultSellingUOM");

                    b.Navigation("DefaultUOM");

                    b.Navigation("DefaultWarehouse");

                    b.Navigation("InventoryValidationMethod");

                    b.Navigation("ItemGroup");

                    b.Navigation("ItemType");
                });

            modelBuilder.Entity("MerkERP.Core.Models.StockLedgerTransaction", b =>
                {
                    b.HasOne("MerkERP.Core.Models.Item_cs", "Item")
                        .WithMany("StockLedgerTransactions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MerkERP.Core.Models.WareHouse_cs", "Warehouse")
                        .WithMany("StockLedgerTransactions")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("MerkERP.Core.Models.TableMetaData", b =>
                {
                    b.HasOne("MerkERP.Core.Models.TableName_s", "TableName")
                        .WithMany()
                        .HasForeignKey("TableNameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TableName");
                });

            modelBuilder.Entity("MerkERP.Core.Models.UOMConversionFactor_cs", b =>
                {
                    b.HasOne("MerkERP.Core.Models.UOMConversionGroup_cs", "UOMConversionGroup")
                        .WithMany()
                        .HasForeignKey("UOMConversionGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MerkERP.Core.Models.UOM_cs", "UOMFrom")
                        .WithMany()
                        .HasForeignKey("UOMFromId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MerkERP.Core.Models.UOM_cs", "UOMTo")
                        .WithMany()
                        .HasForeignKey("UOMToId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UOMConversionGroup");

                    b.Navigation("UOMFrom");

                    b.Navigation("UOMTo");
                });

            modelBuilder.Entity("MerkERP.Core.Models.WareHouseCategory_cs", b =>
                {
                    b.HasOne("MerkERP.Core.Models.WareHouseType_s", "WareHouseType")
                        .WithMany()
                        .HasForeignKey("WareHouseTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("WareHouseType");
                });

            modelBuilder.Entity("MerkERP.Core.Models.WareHouse_cs", b =>
                {
                    b.HasOne("MerkERP.Core.Models.WareHouse_cs", "ParentWarehouse")
                        .WithMany("Children")
                        .HasForeignKey("ParentWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MerkERP.Core.Models.WareHouseCategory_cs", "WareHouseCategory")
                        .WithMany()
                        .HasForeignKey("WareHouseCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MerkERP.Core.Models.WareHouseType_s", "WareHouseType")
                        .WithMany()
                        .HasForeignKey("WareHouseTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentWarehouse");

                    b.Navigation("WareHouseCategory");

                    b.Navigation("WareHouseType");
                });

            modelBuilder.Entity("MerkERP.Core.Models.WarehouseTransaction", b =>
                {
                    b.HasOne("MerkERP.Core.Models.Item_cs", "Item")
                        .WithMany("WarehouseTransactions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MerkERP.Core.Models.WareHouse_cs", "Warehouse")
                        .WithMany("Transactions")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("MerkERP.Core.Models.ItemGroup_cs", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("MerkERP.Core.Models.ItemType_s", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MerkERP.Core.Models.Item_cs", b =>
                {
                    b.Navigation("Barcodes");

                    b.Navigation("StockLedgerTransactions");

                    b.Navigation("UOMConversions");

                    b.Navigation("WarehouseTransactions");
                });

            modelBuilder.Entity("MerkERP.Core.Models.UOM_cs", b =>
                {
                    b.Navigation("Conversions");

                    b.Navigation("DefaultForItems");
                });

            modelBuilder.Entity("MerkERP.Core.Models.WareHouse_cs", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("StockLedgerTransactions");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
